version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    container_name: cystore-nginx
    networks:
      - cystore_network
    depends_on:
      - storereact
      - accountservice
      - inventoryservice
      - shoppingservice
    restart: unless-stopped

  accountservice:
    build:
      context: .
      dockerfile: src/Store/AccountService/Dockerfile
    image: theeknockdocker/accountservice:latest
    container_name: accountservice
    networks:
      - cystore_network

  inventoryservice:
    build:
      context: .
      dockerfile: src/Store/InventoryService/Dockerfile
    image: theeknockdocker/inventoryservice:latest
    container_name: inventoryservice
    networks:
      - cystore_network

  shoppingservice:
    build:
      context: .
      dockerfile: src/Store/ShoppingService/Dockerfile
    image: theeknockdocker/shoppingservice:latest
    container_name: shoppingservice
    networks:
      - cystore_network

  storereact:
    build:
      context: .
      dockerfile: src/Store/store.webreact/Dockerfile
    image: theeknockdocker/storereact:latest
    container_name: storereact
    networks:
      - cystore_network

networks:
  cystore_network:
    driver: bridge